### ISSUE TITLE
mlp in baselines.deepq.models has been removed

### ISSUE THREAD

**Issue by hanegawa** [mengf1/DHER#1]
Dy_snake使用Baselines的mlp方法但新版本已经将此方法移除，可将源代码中mlp._mlp方法粘过来或者使用旧版本的Baselines，特此标注，希望后来的同学不要踩坑哦~(#^.^#)

**Comment by mengf1** [comment]
Please follow our readme and use gym (ver-0.10.9) and baselines (ver-0.1.5).

**Comment by ruoqizzz** [comment]
For other users, I suggest that add the packages' version in file [dher/setup.py](https://github.com/mengf1/DHER/blob/master/dher/setup.py).
